// export const ACTION_DESCRIPTION = "ACTION_DESCRIPTION";

export const TOGGLE_SHOWING_INFO_WINDOW = 'TOGGLE_SHOWING_INFO_WINDOW';
export const ADD_MARKET = 'ADD_ACTIVE_MARKER';
export const DELETE_CARD = 'ADD_SELECTED_PLACE';