// export const ACTION_DESCRIPTION = “ACTION_DESCRIPTION”;

export const ADD_SEARCH = 'ADD_SEARCH';
export const ADD_LOCATIONS = 'ADD_LOCATIONS';
export const SET_CURR_LOCATION = 'SET_CURR_LOCATION';
export const SELECT_MARKER = 'SELECT_MARKER';
export const SET_MARKERS = 'SET_MARKERS';
export const DESELECT = 'DESELECT';
export const SET_LOGIN = 'SET_LOGIN';
